name: sample-dockerfile
services:
- dockerfile_path: Dockerfile
  name: sample-dockerfile
  http_port: 8200
  envs:
  - key: SKIP_SETCAP
    scope: RUN_AND_BUILD_TIME
    value: true
  github:
    branch: main
    deploy_on_push: true
    repo: fire/gray-tin-vulture-dockerfile